### ISSUE TITLE
RDF feed support not implemented

### ISSUE THREAD

**Issue by robinspi** [rubenwardy/renewedtab#5]
Sorry for not posting in GitLab, don't use it yet

As the title says, Renewed Tab fails to parse RDF feeds, and just throws an error. Would love to use RDF feeds in the Feed section as well. Example use case feed: https://nvd.nist.gov/feeds/xml/cve/misc/nvd-rss-analyzed.xml

Thanks.

**Comment by rubenwardy** [comment]
Hi, thanks for the request. I've not heard of RDF feeds before, I'll take a look into it

**Comment by rubenwardy** [comment]
I've implemented this now. It'll be released as part of 1.14.0 in the next week or so
